### ISSUE TITLE
pwnx.io - Challenge JURRASIC TRAVEL

### ISSUE THREAD

**Issue by eltoro0815** [D3vil0per/timeverter#2]
Hi:) I'm using this way to inform you, that the password of piero has been changed by someone.

I achieved the user flag and wanted to continue with the root challenge.

I was able to save the Earth and went where piero was. But this is no longer possible.

**Comment by D3vil0p3r** [comment]
@eltoro0815 reach me here: https://discord.gg/DNjvQkb5Ad
